# Generated by Django 3.2.7 on 2021-09-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210930_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_cat',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default='nothing.jpg', upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sub_category'),
        ),
    ]
