# Generated by Django 3.2.7 on 2021-09-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210930_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
