# Generated by Django 3.2.7 on 2021-09-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_prod_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_name',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sub_category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
