# Generated by Django 3.2.7 on 2021-10-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211016_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
