# Generated by Django 3.2.7 on 2021-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_cart_is_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('delievered', 'Delievered'), ('out for delievery', 'Out for delievery')], default='Pending', max_length=255, null=True),
        ),
    ]
