# Generated by Django 3.2.7 on 2021-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211111_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('delievered', 'Delievered'), ('out for delievery', 'Out for delievery')], default='pending', max_length=255, null=True),
        ),
    ]
