# Generated by Django 3.2.7 on 2021-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliever_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
