# Generated by Django 3.2.7 on 2021-11-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_order_deliever_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(null=True, to='products.Cart'),
        ),
    ]
