# Generated by Django 3.2.7 on 2021-11-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
