# Generated by Django 3.2.7 on 2021-11-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20211121_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'pending'), ('Delievered', 'delievered'), ('Out for delievery', 'out for delievery')], default='Pending', max_length=255, null=True),
        ),
    ]
