# Generated by Django 3.2.7 on 2021-11-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20211123_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
