# Generated by Django 3.2.7 on 2021-12-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_order_payment_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_process',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept')], default='pending', max_length=30),
        ),
    ]
