# Generated by Django 3.2.7 on 2022-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_order_payment_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_process',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='pending', max_length=30),
        ),
    ]
