# Generated by Django 3.2.7 on 2022-01-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20220108_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='return_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
